# name: Linting

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

#   workflow_dispatch:

# jobs:
#   check:
#     runs-on: ubuntu-20.04

#     steps:
#       - name: Checking out repo
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: make venv

#       - name: Linting
#         run: make lint
